project_id = "ovnmwhzlwgfvrrjxuplp"

[functions.enviar-orcamento]
verify_jwt = true

[functions.enviar-fatura]
verify_jwt = true

[functions.criar-checkout-stripe]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false