project_id = "ovnmwhzlwgfvrrjxuplp"

[functions.enviar-email-boas-vindas]
verify_jwt = false

[functions.excluir-conta]
verify_jwt = true

[functions.enviar-orcamento]
verify_jwt = true

[functions.enviar-fatura]
verify_jwt = true

[functions.criar-checkout-stripe]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false